name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  check:
    name: Check & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo test

  create-release:
    name: Create GitHub Release
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Essential for changelog history

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          generate_release_notes: true
